-- The data is generated by some random generator.
-- Any resemblance to actual persons, living or dead, is purely coincidental.

insert into Groups values (0, 'M3436');
insert into Groups values (1, 'M3437');
insert into Groups values (2, 'M3439');
insert into Groups values (3, 'M3139');
insert into Groups values (4, 'M3234');
insert into Groups values (5, 'M1337');
insert into Groups values (6, 'M1488');
insert into Groups values (7, 'M228');
insert into Groups values (8, 'Отчислен (лох)');

insert into Students values (0, 'Гизатуллин Айдар', 0); 
insert into Students values (1, 'Максимовских Анастасия', 1);
insert into Students values (2, 'Семёнов Вадим', 1);
insert into Students values (3, 'Подтёлкин Владислав', 2);
insert into Students values (4, 'Жолус Артём', 2);
insert into Students values (5, 'Стандрей Горнеев', 0);
insert into Students values (6, 'Плавал Пловец', 2);
insert into Students values (7, 'Первокурсник Первокурсников', 3);
insert into Students values (8, 'Диплом Вколенович', 1);
insert into Students values (9, 'Лена Головач', 4);
insert into Students values (10, 'Второкурсник Второкурсников', 4);
insert into Students values (11, 'Дело Делович', 0);
insert into Students values (12, 'Дрёмин Иван', 3);
insert into Students values (13, 'Влад Каменев', 1);
insert into Students values (14, 'Александр Трубин', 8);
insert into Students values (15, 'Джон Сина', 7);

insert into Courses values (0, 'Базы данных');
insert into Courses values (1, 'Функциональное программирование');
insert into Courses values (2, 'Математическая логика');
insert into Courses values (3, 'Теория типов');
insert into Courses values (4, 'Введение в программирование');
insert into Courses values (5, 'Алгебра и геометрия');
insert into Courses values (6, 'Алгоритмы и структуры данных');
insert into Courses values (7, 'Философия');
insert into Courses values (8, 'Языки программирования');
insert into Courses values (9, 'Архитектура ЭВМ');
insert into Courses values (10, 'Сети)))');
insert into Courses values (11, 'Физкультура');
insert into Courses values (12, 'Теология Плюсов');

insert into Lecturers values (0, 'Корнеев Георгий');
insert into Lecturers values (1, 'Кованников Дмитрий');
insert into Lecturers values (2, 'Серока Арсений');
insert into Lecturers values (3, 'Штукенберг Дмитрий');
insert into Lecturers values (4, 'Ирина Ломова');
insert into Lecturers values (5, 'Иван Сорокин');
insert into Lecturers values (6, 'Чирцов');
insert into Lecturers values (7, 'Нияз Нигматуллин');
insert into Lecturers values (8, 'Александр Рыжков');
insert into Lecturers values (9, 'Владимир Путин');
insert into Lecturers values (10, 'Алексей Навальный');
insert into Lecturers values (11, 'Павел Скаков');
insert into Lecturers values (12, 'Анатолий Васильев');

insert into Plan values (0, 0, 0);
insert into Plan values (1, 0, 0);
insert into Plan values (2, 0, 0);
insert into Plan values (2, 1, 1);
insert into Plan values (2, 1, 2);
insert into Plan values (2, 2, 3);
insert into Plan values (2, 3, 3);
insert into Plan values (0, 7, 4);
insert into Plan values (1, 7, 4);
insert into Plan values (3, 4, 0);
insert into Plan values (3, 5, 8);
insert into Plan values (3, 6, 7);
insert into Plan values (3, 6, 12);
insert into Plan values (3, 9, 11);

insert into Marks values (3, 0, 99.5);
insert into Marks values (0, 0, 60.0);
insert into Marks values (3, 1, 99.9);
insert into Marks values (3, 2, 100);
insert into Marks values (3, 3, 60.0);
insert into Marks values (2, 0, 60.0);
insert into Marks values (1, 7, 60.0);
